### PR TITLE
Improvements with Maven and Hawk API

### PR DESCRIPTION
**Pull request by funkemunky**
- Converted Hawk's project structure to Maven. It should be pretty much drag and drop now for anyone wanting to work on Hawk, no matter the IDE.
- Made HawkFlagEvent optionally cancellable. 
- Part of the alerts (the logging and broadcast part) runs separately from the checking thread. This is usually the most laggy part of an anticheat.
- Lombok is now a thing. use it for your getters, setters, and constructors. Trust me, its very helpful. You can also use var, and val field names. This will basically automatically compile with the appropriate identifier for fields. val is for final fields, and var is for non-final fields.

### CODE REVIEW

**Comment by Islandscout** [comment]
I'm gonna have to think this through a little bit. I'm a little hesitant about using Lombok.

**Comment by FozzieHi** [comment]
@funkemunky probably should have split these features up into multiple PRs.

**Comment by retrooper** [comment]
I personally also wouldn't really like Lombok. (atm, maybe ill regret in the future 👍 )
But funke defo should have split these commits into different branches/PRs.

**Comment by Islandscout** [comment]
Well this isn't gonna work. Sorry man, though I appreciate the PR, and sorry for not getting back after 16 months.

**Comment by retrooper** [comment]
haha

**Comment by Tecnio** [comment]
bruh

**Comment by thehydrogen** [comment]
rip

**Comment by FINE-V3rm** [comment]
after 16 months

**Comment by retrooper** [comment]
packetevents

**Pull request closed without merging**
